name: CI_pytest_appendfilename

# name    : pytest.yml
# purpose : regularly run pytest on appendfilename
# date    : [2024-10-31 Thu]
# edit    : [2024-10-31 Thu]

on:
  push:
    branches:
      - master           # additions to the principal branch "master"
  pull_request:
    branches:
      - master           # PRs to enter the principal branch "master"
  workflow_dispatch:     # provide a manual trigger
  # schedule:
    # - cron: "0 0 1 * *"  # once each 1st of a month, at 00:00 UTC (cf. https://crontab.guru/)

jobs:
  test-ubuntu-2404:
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        # by [2024-10-23 Wed], this version possibly will be considered "old", cf.
        # https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies with PyPI
        run: pip install -r requirements.txt

      - name: run the check by pytest
        run: |
          python -m pytest -m "default"
          python -m pytest -m "prepend"
          python -m pytest -m "smart"

  test-windows-2022:
    runs-on: windows-2022
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        # by [2024-10-23 Wed], this version possibly will be considered "old", cf.
        # https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies with PyPI
        run: pip install -r requirements.txt

      - name: run the check by pytest
        run: |
          python -m pytest -m "default"
          python -m pytest -m "prepend"
          python -m pytest -m "smart"


  test-macos-14:
    runs-on: macos-14
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        # by [2024-10-23 Wed], this version possibly will be considered "old", cf.
        # https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies with PyPI
        run: pip install -r requirements.txt

      - name: run the check by pytest
        run: |
          python -m pytest -m "default"
          python -m pytest -m "prepend"
          python -m pytest -m "smart"

